name: Audit Notebooks

on:
  push:
    paths:
      - 'notebooks/**'
      - 'audit_notebooks.py'
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pandas nbformat
      - name: Run audit
        run: python audit_notebooks.py
      - name: Commit results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add notebook_audit.csv notebook_summary.md || true
          git commit -m "chore: update notebook audit" || echo "No changes to commit"
          git push
